### ISSUE TITLE
여섯시에서 여덟의 '여'에 불이 들어오는 문제

### ISSUE THREAD

**Issue by nayunhwan** [dsa28s/mac-hanguldesktop-clock#1]
![image](https://cloud.githubusercontent.com/assets/7167731/22731345/a99a013e-ee2d-11e6-8a0d-64252e59f748.png)

위와 같은 버그가 발견되었습니다.

**Comment by dsa28s** [comment]
빌드 154 (v 1.4.1) 에서 해결했습니다!
Solved Issue in BUILD 154 (v 1.4.1)
