### ISSUE TITLE
문구 customizing

### ISSUE THREAD

**Issue by Kcrong** [dsa28s/mac-hanguldesktop-clock#2]
![image](https://cloud.githubusercontent.com/assets/13450715/22871902/84af0fee-f1f8-11e6-94ea-b72082deee84.png)

시계 상단 문구 (~ 나는 네가 제일 좋아, 오늘도 수고했어 등) 를 사용자가 바꿀 수 있는 기능이 있으면 좋을 것 같습니다.

**Comment by wootrio** [comment]
멋진 아이디어입니다. 응원합니다

**Comment by dsa28s** [comment]
피드백 감사합니다 :) 지금은 윈도우 버전이 출시되서 열심히 버그잡고 있습니다. 잡히는 대로 바로 반영하겠습니다!

**Comment by dsa28s** [comment]
커스터마이징 기능 추가했어요! 감사합니다~

**Comment by Kcrong** [comment]
넵 수고하셨습니다 :)
