### ISSUE TITLE
How unistall this? How to delete all clean?

### ISSUE THREAD

**Issue by JaekwangSong** [dsa28s/mac-hanguldesktop-clock#4]
while installing, including node.js etc.. some stuffs installed together..
Now I wanna uninstall this and clear up all the stuffs...
Let me know how..
thank you.

기본 설치시 노드js등.. 이것저것 많이 깔리는데, 
삭제를 하려면 어떻게 해야하나요??
완전히 모든 설치물들이 삭제되는 건가요??

**Comment by dsa28s** [comment]
설치기 오류로 인해
완벽한 제거를 위해서는 C:\Program Files\Hangul Clock 폴더를 지워주시면 완벽히 제거가 가능하며
Node.js 는 사용하지 않으실 경우 프로그램 추가/제거에서 지워주시면 됩니다.

제가 고3인지라 시간이 된다면 Node.js 와의 의존성 없이 독립시킬 예정입니다.
불편을 드려 죄송합니다.

**Comment by dsa28s** [comment]
윈도우일 경우만 해당됩니다.

**Comment by JaekwangSong** [comment]
Thank you~!!
잘쓰다가 지우게 되었습니다.
이상하게 계속 켜두면 하루 정도 지나면 메모리가 2~3GB 잡아먹고 있네요..
첨에는 문제가 없는데 리소스를 점점 잡아 먹어서 지우게 되었습니다.

아주 조금씩 메모리 누수가 생기는 것 같습니다만, 잡기가 쉽지 않은 부분일지도 모르겠네요..

감사합니다~!
