### ISSUE TITLE
실행 오류

### ISSUE THREAD

**Issue by jmhjkh0410** [dsa28s/mac-hanguldesktop-clock#5]
시에라 10.12.6에서 실행시 실행이 않되고 아무 반응이 없네요

**Comment by FuZer** [comment]
동일 문제가 발생합니다. 
![image](https://user-images.githubusercontent.com/17673616/30731203-fb40cf88-9fa6-11e7-9e2b-f2b72d1e55c4.png)

**Comment by hey-jude** [comment]
저는 압축파일 오류 메시지 한번 보고 나서 실행이 안됩니다.

**Comment by hey-jude** [comment]
@dsa28s 아, 위 압축파일은 잘 실행됩니다. 참고로 전 시에라.

**Comment by FuZer** [comment]
@dsa28s 실행 잘 됩니다. :)

**Comment by dsa28s** [comment]
감사합니다!!
