### ISSUE TITLE
README.md에 스크린샷이 안나와요

### ISSUE THREAD

**Issue by ChangJoo-Park** [dsa28s/mac-hanguldesktop-clock#6]
안녕하세요 

README.md 파일에 스크린샷이 안나와서 이슈 등록합니다

`![텍스트](이미지 URL)`을 사용하시면 이미지를 README에서 볼 수 있습니다

**Comment by dsa28s** [comment]
앗, 커밋하다보니 스크린샷이 누락되었네요ㅠㅠㅠㅠ 곧 업데이트 하면서 수정하겠습니다~~~

**Comment by ChangJoo-Park** [comment]
네 감사합니다 :+1:
