### ISSUE TITLE
Manual(ReadMe) 대로 했으나, 최신버전인 High Sierra(10.13)에서 실행이...

### ISSUE THREAD

**Issue by YBHwang** [dsa28s/mac-hanguldesktop-clock#7]
Manual(ReadMe) 대로 했으나
최신버전인 High Sierra(10.13)에서 실행이 불가능...
실행시켜도 아무런 변화가 없습니다. 버그가 맞나요?

**Comment by dsa28s** [comment]
현재 제가 사용하는 맥 버전도 10.13인데, 실행은 되나 바탕화면에 아무것도 안나오신다는 말씀이신가요??

**Comment by YBHwang** [comment]
다운로드 : https://hangulclock.today
링크에서 다운받았을때와 직접다운로드 링크의 파일이 일치하지 않았었습니다.

**Comment by YBHwang** [comment]
지금은 정상적입니다ㅎ

**Comment by dsa28s** [comment]
으아, 홈페이지도 업데이트 해야겠네요 :) 감사합니다!
