### ISSUE TITLE
열한시 일분 표시 버그 같습니다. 

### ISSUE THREAD

**Issue by nuxlear** [dsa28s/mac-hanguldesktop-clock#8]
![image](https://user-images.githubusercontent.com/16524489/31445120-6aec58bc-aed8-11e7-823f-d90497354054.png)

아래
정**일**이삼사육
오오칠팔구분
에 있는 '일' 글자가 들어와야 할 거 같은데 위에 시를 나타내는 부분에 뜨네요. 

전에 11:01 외에도 열X시 X분 인 경우 가끔씩 뜨던 버그인 것 같은데 확인 부탁드릴게요.

**Comment by dsa28s** [comment]
v 2.0.5 에서 해결 했습니다!! 업데이트 부탁드릴게요!

**Comment by nuxlear** [comment]
아 제가 업데이트를 안하고 사용하고 있었네요 ㅎㅎ 감사합니다!
항상 잘 쓰고 있습니다~
